# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b578f94d872d83ba56ea8f2545da4c3880e79eb76149029278a3be8477df0d76db522b485d052bd0a642dd723be1df00aaaa3c0067a80fd711011ca976619025

test:
  secret_key_base: 084dce5a8012fb5f29b4a6731e33ff0bafcbf393288b4faf9d4e2cc35a039c71cbc1318819c6930c2ce2000cf3d694517c26e8a22f6eb77c320636c7654d448c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
